# Uncomment this line to define a global platform for your project
platform :ios, "8.0"
use_frameworks!

target "SmartAgent" do
pod 'Firebase', '~> 3.2'
pod 'FirebaseAuth', '~> 3.0'
pod 'Firebase/Messaging'
pod 'Fabric'
pod 'Crashlytics', '~> 3.7'
pod 'Alamofire', '~> 3.4'
pod 'AMScrollingNavbar', '~> 2.1'
pod 'PKHUD', '~> 3.1'
pod 'RealmSwift', '~> 1.0'
pod 'RxSwift',    '~> 2.0'
pod 'RxCocoa',    '~> 2.0'
pod 'KeychainAccess', '~> 2.3'
end

