# Uncomment this line to define a global platform for your project
platform :ios, "8.0"
use_frameworks!

target "LogNet" do
pod 'Firebase', '~> 3.2'
pod 'FirebaseAuth', '~> 3.0'
pod 'Firebase/Messaging'
pod 'Fabric'
pod 'Crashlytics'
pod 'ReactiveCocoa', '~> 4.1'
pod 'Alamofire', '~> 3.4'
pod 'AMScrollingNavbar', '~> 2.1'
end

